### ISSUE TITLE
Does not help to pass the exam 70-486

### ISSUE THREAD

**Issue by ChRocheFR** [MicrosoftLearning/20486-DevelopingASPNETMVCWebApplications#23]
This course is just a light copy and paste from the initial release with Visual Studio 2012 and does not cover most of the points needed for the certification. What about .Net Core? ASP.NET Identity?...

**Comment by barucht** [comment]
Hi,

The aim of this course was to update the 2012 version to .NET 4.7 and VS2015.
A brand new ASP.NET Core course is being released in about two weeks time, you can already get its GitHub repository from:
https://github.com/MicrosoftLearning/20486D-DevelopingASPNETMVCWebApplications

HTH.

**Comment by ChRocheFR** [comment]
Hi, 
Thank you for this comment. I'm pretty sure this will help my clients for the future.
